name: Publish

on:
  schedule:
    # Every 30 minutes
    - cron: '*/30 * * * *'
  workflow_call:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
        env:
          TERMINUSDB_API_TOKEN: ${{ secrets.TERMINUSDB_API_TOKEN }}
      - run: python3 convert_to_dirs.py
      - run: curl -X POST ${{ secrets.CLOUDFLARE_DEPLOY_HOOK }} -o /dev/null
